### ISSUE TITLE
Switch samples/snippets/pom.xml to use libraries-bom

### ISSUE THREAD

**Issue by chingor13** [googleapis/java-mediatranslation#10]
We cannot suggest using the libraries-bom here until this library is included in the libraries-bom

**Comment by suztomo** [comment]
https://search.maven.org/artifact/com.google.cloud/google-cloud-mediatranslation/0.7.10/jar is still pre-GA.

**Comment by suztomo** [comment]
But somehow it's part of the Google Cloud BOM...

**Comment by suztomo** [comment]
Obsolete.
