### ISSUE TITLE
Missing method getRecognitionResult()

### ISSUE THREAD

**Issue by p4paul** [googleapis/java-mediatranslation#629]
Great library!  I have been playing with a few different foreign news sites and it seems to work well.

I noticed that there is a missing method to fetch the untranslated 'source' text.

In your example file: https://github.com/googleapis/java-mediatranslation/blob/HEAD/samples/snippets/src/main/java/com/example/mediatranslation/TranslateFromMic.java

````
    StreamingTranslateSpeechResult res = response.getResult();
    String translation = res.getTextTranslationResult().getTranslation();
    String source = res.getRecognitionResult();
````
There is no method **getRecognitionResult()**?

**Comment by p4paul** [comment]
Found the method in old jar: 
  com.google.cloud:google-cloud-mediatranslation:0.3.2

Missing in jar: 
  com.google.cloud:google-cloud-mediatranslation:0.4.0

**Comment by kweinmeister** [comment]
Hi @p4paul, yes, this field is not currently supported, and was removed in 0.4.0. I have created a PR to update the samples accordingly. Thanks for raising this!
